### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by mojicaj** [chingu-voyage4/Bears-Team-27#5]

**Comment by mojicaj** [comment]
user login
input form
list organization
list editing
list export options
item value/totals
item tracking

**Comment by msksfo** [comment]
form input for item name
form input for short description
form input for item value
form input for date purchased/received
form input for serial number if applicable
form input for warranty details if applicable

**Comment by msksfo** [comment]
extra if we have time is to let the user change currency. ie euro, peso, krona
if we have time, add functionality to keep track of who has borrowed items

**Comment by jhoover4** [comment]
uploading and association a picture with item
organize items by location
associating a receipt with an item
